version: '2'


networks:
  basic:


services:

 # 基础组件

  redis:
    image: redis
    container_name: redis
    ports:
    - "6379:6379"
    environment: 
    - TZ=Asia/Shanghai
    volumes:
    - /jbh/redis/data/:/data:Z
    networks:
      - basic


  mysql:
    image: mysql:5.6
    container_name: mysql
    ports:
    - "3306:3306"
    environment:
    - TZ=Asia/Shanghai
    - MYSQL_ROOT_PASSWORD=root
    volumes:
    - /jbh/mysql/data/:/var/lib/mysql:Z
    networks:
      - basic

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
    - "5672:5672"
    - "15672:15672"
    environment:
    - TZ=Asia/Shanghai
    networks:
      - basic



 # service frame

  eureka:
    image: adoptopenjdk/openjdk8-openj9
    container_name: eureka
    ports:
    - "9999:9999"
    environment:
    - TZ=Asia/Shanghai
    volumes:
    - /jbh/servers/data/eureka.jar:/jbh/data/application.jar:Z
    - /jbh/servers/data/eureka.properties:/jbh/data/application.properties:Z
    - /jbh/servers/log/:/serviceframe/log/:Z
    command: java -jar /jbh/data/application.jar --spring.config.location=/jbh/data/application.properties >/dev/null 2>&1 & && tail -f /dev/null
    networks:
      - basic


  config:
    image: adoptopenjdk/openjdk8-openj9
    container_name: config
    ports:
    - "9998:9998"
    environment:
    - TZ=Asia/Shanghai
    volumes:
    - /jbh/servers/data/config.jar:/jbh/data/application.jar:Z
    - /jbh/servers/data/config.properties:/jbh/data/application.properties:Z
    - /jbh/servers/log/:/serviceframe/log/:Z
    command: java -jar /jbh/data/application.jar --spring.config.location=/jbh/data/application.properties >/dev/null 2>&1 & && tail -f /dev/null
    networks:
      - basic
    links:
    - eureka


  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
    - "9411:9411"
    environment:
    - TZ=Asia/Shanghai
    - zipkin.collector.rabbitmq.addresses=rabbitmq
    - zipkin.collector.rabbitmq.username=guest
    - zipkin.collector.rabbitmq.password=guest
    volumes:
    - /jbh/servers/data/zipkin.jar:/jbh/data/application.jar:Z
    command: java -jar /jbh/data/application.jar >/dev/null 2>&1 & && tail -f /dev/null
    networks:
      - basic
    links:
    - eureka


  admin:
    image: adoptopenjdk/openjdk8-openj9
    container_name: admin
    ports:
    - "9997:9997"
    environment:
    - TZ=Asia/Shanghai
    volumes:
    - /jbh/servers/data/admin.jar:/jbh/data/application.jar:Z
    - /jbh/servers/data/admin.properties:/jbh/data/application.properties:Z
    - /jbh/servers/log/:/serviceframe/log/:Z
    command: java -jar /jbh/data/application.jar --spring.config.location=/jbh/data/application.properties >/dev/null 2>&1 & && tail -f /dev/null
    networks:
      - basic
    links:
    - eureka
    - zipkin
    - config


  hystrix:
    image: adoptopenjdk/openjdk8-openj9
    container_name: hystrix
    ports:
    - "9996:9996"
    environment:
    - TZ=Asia/Shanghai
    volumes:
    - /jbh/servers/data/hystrix.jar:/jbh/data/application.jar:Z
    - /jbh/servers/data/hystrix.properties:/jbh/data/application.properties:Z
    - /jbh/servers/log/:/serviceframe/log/:Z
    command: java -jar /jbh/data/application.jar --spring.config.location=/jbh/data/application.properties >/dev/null 2>&1 & && tail -f /dev/null
    networks:
      - basic
    links:
    - eureka
    - zipkin
    - config












