version: '2'


networks:
  basic:


services:

 # 基础组件

  redis:
    image: redis
    container_name: redis
    ports:
    - "6379:6379"
    environment: 
    - TZ=Asia/Shanghai
    volumes:
    - /srv/redis/data/:/data:Z
    networks:
      - basic


  mysql:
    image: mysql:5.6
    container_name: mysql
    ports:
    - "3972:3306"
    environment:
    - TZ=Asia/Shanghai
    - MYSQL_ROOT_PASSWORD=sERviCefRaMe
    volumes:
    - /srv/mysql/data/:/var/lib/mysql:Z
    networks:
      - basic

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
    - "5672:5672"
    - "15672:15672"
    environment:
    - TZ=Asia/Shanghai
    networks:
      - basic



 # service frame

  eureka:
    image: adoptopenjdk/openjdk8-openj9
    container_name: eureka
    ports:
    - "9999:9999"
    environment:
    - TZ=Asia/Shanghai
    volumes:
    - /srv/framework/data/eureka.jar:/srv/data/application.jar:Z
    - /srv/framework/data/eureka.properties:/srv/data/application.properties:Z
    - /srv/framework/log/:/serviceframe/log/:Z
    command: java -jar /srv/data/application.jar --spring.config.location=/srv/data/application.properties >/dev/null 2>&1 & && tail -f /dev/null
    networks:
      - basic


  config:
    image: adoptopenjdk/openjdk8-openj9
    container_name: config
    ports:
    - "9998:9998"
    environment:
    - TZ=Asia/Shanghai
    volumes:
    - /srv/framework/data/config.jar:/srv/data/application.jar:Z
    - /srv/framework/data/config.properties:/srv/data/application.properties:Z
    - /srv/framework/log/:/serviceframe/log/:Z
    command: java -jar /srv/data/application.jar --spring.config.location=/srv/data/application.properties >/dev/null 2>&1 & && tail -f /dev/null
    networks:
      - basic
    links:
    - eureka

  nacos:
    image: nacos/nacos-server
    container_name: nacos
    ports:
    - "8848:8848"
    environment:
    - TZ=Asia/Shanghai
    - MODE=standalone
    - MYSQL_SERVICE_HOST=mysql
    - MYSQL_SERVICE_PORT=3306
    - MYSQL_SERVICE_DB_NAME=nacos_config
    - MYSQL_SERVICE_USER=root
    - MYSQL_SERVICE_PASSWORD=root
    networks:
    - basic
    links:
    - mysql

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
    - "9411:9411"
    environment:
    - TZ=Asia/Shanghai
    - zipkin.collector.rabbitmq.addresses=rabbitmq
    - zipkin.collector.rabbitmq.username=guest
    - zipkin.collector.rabbitmq.password=guest
    volumes:
    - /srv/framework/data/zipkin.jar:/srv/data/application.jar:Z
    command: java -jar /srv/data/application.jar >/dev/null 2>&1 & && tail -f /dev/null
    networks:
      - basic
    links:
    - nacos


  admin:
    image: adoptopenjdk/openjdk8-openj9
    container_name: admin
    ports:
    - "9997:9997"
    environment:
    - TZ=Asia/Shanghai
    volumes:
    - /srv/framework/data/admin.jar:/srv/data/application.jar:Z
    - /srv/framework/data/admin.properties:/srv/data/application.properties:Z
    - /srv/framework/log/:/serviceframe/log/:Z
    command: java -jar /srv/data/application.jar --spring.config.location=/srv/data/application.properties >/dev/null 2>&1 & && tail -f /dev/null
    networks:
      - basic
    links:
    - nacos
    - zipkin


  hystrix:
    image: adoptopenjdk/openjdk8-openj9
    container_name: hystrix
    ports:
    - "9996:9996"
    environment:
    - TZ=Asia/Shanghai
    volumes:
    - /srv/framework/data/hystrix.jar:/srv/data/application.jar:Z
    - /srv/framework/data/hystrix.properties:/srv/data/application.properties:Z
    - /srv/framework/log/:/serviceframe/log/:Z
    command: java -jar /srv/data/application.jar --spring.config.location=/srv/data/application.properties >/dev/null 2>&1 & && tail -f /dev/null
    networks:
      - basic
    links:
    - nacos
    - zipkin


  skywalking-aop:
    image: apache/skywalking-oap-server
    container_name: skywalking-aop
    ports:
    - "11800:11800"
    - "12800:12800"
    environment:
    - TZ=Asia/Shanghai
    networks:
    - basic


  skywalking-ui:
    image: apache/skywalking-ui
    container_name: skywalking-ui
    ports:
    - "8880:8080"
    environment:
    - TZ=Asia/Shanghai
    - SW_OAP_ADDRESS=skywalking-aop:12800
    networks:
    - basic
    links:
    - skywalking-aop






